default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  host: localhost

development:
  <<: *default
  database: test_guru_development

test:
  <<: *default
  database: test_guru_test

production:
  <<: *default
  database: test_guru_prod
